# Generated by Django 5.1.3 on 2025-06-13 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasApp', '0002_unidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('producto_id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=40)),
                ('estado', models.CharField(max_length=1)),
                ('stock', models.FloatField()),
                ('precio', models.FloatField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventasApp.categoria')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventasApp.unidad')),
            ],
        ),
    ]
