# Generated by Django 5.2.3 on 2025-06-30 21:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasApp', '0003_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.AutoField(primary_key=True, serialize=False)),
                ('ruc_dni', models.CharField(max_length=11)),
                ('nombres', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField(default=0)),
                ('cantidad', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'detalleventa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('idtipo', models.AutoField(primary_key=True, serialize=False)),
                ('numeracion', models.CharField(max_length=15)),
                ('serie', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'parametros',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaventa', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.IntegerField(default=1)),
                ('total', models.FloatField(default=0)),
                ('nrodoc', models.CharField(max_length=12)),
                ('subtotal', models.FloatField(default=0)),
                ('igv', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'cabeceraventa',
                'managed': False,
            },
        ),
    ]
